ITEM.Name = "Caixa da Butterfly"
ITEM.Price = 5000
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(100, 255, 0)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "butterfly_key"

ITEM.PossibleItems = {
    ["csgo_butterfly"] = 10,
    ["csgo_butterfly_am_marble_fade"] = 10,
    ["csgo_butterfly_night"] = 10,
    ["csgo_butterfly_blackpearl"] = 10,
    ["csgo_butterfly_bluesteel"] = 10,
    ["csgo_butterfly_boreal"] = 10,
    ["csgo_butterfly_case"] = 10,
    ["csgo_butterfly_bright_water"] = 10,
    ["csgo_butterfly_crimsonwebs"] = 10,
    ["csgo_butterfly_damascus"] = 10,
    ["csgo_butterfly_ddpat"] = 10,
    ["csgo_butterfly_doppler_phase1"] = 10,
    ["csgo_butterfly_doppler_phase2"] = 10,
    ["csgo_butterfly_doppler_phase3"] = 10,
    ["csgo_butterfly_doppler_phase4"] = 10,
    ["csgo_butterfly_doppler_ruby"] = 10,
    ["csgo_butterfly_doppler_sapphire"] = 10,
    ["csgo_butterfly_fade"] = 10,
    ["csgo_butterfly_freehand"] = 10,
    ["csgo_butterfly_galaxy"] = 10,
    ["csgo_butterfly_gamma_doppler"] = 10,
    ["csgo_butterfly_marblefade"] = 10,
    ["csgo_butterfly_rustcoat"] = 10,
    ["csgo_butterfly_slaughter"] = 10,
    ["csgo_butterfly_tiger"] = 10,
    ["csgo_butterfly_ultraviolet"] = 10,
    ["points:200"] = 400,
    ["points:1000"] = 150
}