ITEM.Name = "Caixa da Shadow Daggers"
ITEM.Price = 5000
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(0, 255, 100)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "daggers_key"

ITEM.PossibleItems = {
    ["csgo_daggers"] = 10,
    ["csgo_daggers_case"] = 10,
    ["csgo_daggers_boreal"] = 10,
    ["csgo_push_am_marble_fade"] = 10,
    ["csgo_daggers_night"] = 10,
    ["csgo_push_blackpearl"] = 10,
    ["csgo_daggers_bluesteel"] = 10,
    ["csgo_daggers_bright_water"] = 10,
    ["csgo_daggers_webs"] = 10,
    ["csgo_daggers_damascus"] = 10,
    ["csgo_daggers_ddpat"] = 10,
    ["csgo_push_doppler_phase1"] = 10,
    ["csgo_push_doppler_phase2"] = 10,
    ["csgo_push_doppler_phase3"] = 10,
    ["csgo_push_doppler_phase4"] = 10,
    ["csgo_push_doppler_ruby"] = 10,
    ["csgo_push_doppler_sapphire"] = 10,
    ["csgo_daggers_fade"] = 10,
    ["csgo_daggers_freehand"] = 10,
    ["csgo_daggers_gamma_doppler"] = 10,
    ["csgo_daggers_greyscaled"] = 10,
    ["csgo_daggers_marblefade"] = 10,
    ["csgo_daggers_rustcoat"] = 10,
    ["csgo_daggers_slaughter"] = 10,
    ["csgo_daggers_tiger"] = 10,
    ["csgo_daggers_ultraviolet"] = 10,
    ["points:200"] = 400,
    ["points:1000"] = 150
}