FROM ceifa/gmod-server:latest

COPY ./shared /server/garrysmod
COPY ./murder/src /server/garrysmod

ENV NAME="[BR] Lory | Murder ~ Poucos addons ~ Precisamos de staffs ~ Divirta-se!"
ENV ARGS="+host_workshop_collection 1581506103"
ENV MAP="gm_wwhouse"
ENV GAMEMODE="murder"
ENV MAXPLAYERS="24"