FROM ceifa/gmod-server:latest

ADD ../shared /server/garrysmod
ADD ./src /server/garrysmod

ENV HOSTNAME="[BR] Lory | Murder ~ Divirta-se!"
# ENV ARGS="+host_workshop_collection 382793424"
# ENV MAP="deathrun_atomic_warfare"
# ENV GAMEMODE="deathrun"
ENV MAXPLAYERS="24"