FROM ceifa/gmod-server:root

COPY ./shared /server/garrysmod
COPY ./murder/src /server/garrysmod

ENV NAME="[BR] Lory | Murder ~ Antigo DEVX, mas muito melhor ~ Divirta-se!"
ENV ARGS="+host_workshop_collection 1581506103"
ENV MAP="gm_wwhouse"
ENV GAMEMODE="murder"
ENV MAXPLAYERS="24"