FROM ceifa/gmod-server:root

COPY ./_shared /server/garrysmod
COPY ./murder/src /server/garrysmod

ENV NAME="[BR] Lory | Murder ~ [[ VIP GRATIS LIMITADO! ]] ~ Divirta-se!"
ENV ARGS="+host_workshop_collection 1581506103 -tickrate 100"
ENV MAP="gm_wwhouse"
ENV GAMEMODE="murder"
ENV MAXPLAYERS="24"