FROM ceifa/gmod-server:root

COPY ./shared /server/garrysmod
COPY ./deathrun/src /server/garrysmod

ENV NAME="[BR] Lory | Deathrun ~ 128 tickrate ~ Divirta-se!"
ENV ARGS="+host_workshop_collection 382793424 -tickrate 100"
ENV MAP="deathrun_atomic_warfare"
ENV GAMEMODE="deathrun"
ENV MAXPLAYERS="24"