ITEM.Name = "Caixa da M9 Bayonet"
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(225, 225, 225)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "m9_key"

ITEM.PossibleItems = {
    ["csgo_m9"] = 10,
    ["csgo_m9_night"] = 10,
    ["csgo_m9_autotronic"] = 10,
    ["csgo_m9_black_laminate"] = 10,
    ["csgo_m9_blackpearl"] = 6,
    ["csgo_m9_bluesteel"] = 10,
    ["csgo_m9_boreal"] = 10,
    ["csgo_m9_bright_water"] = 10,
    ["csgo_m9_case"] = 10,
    ["csgo_m9_crimsonwebs"] = 10,
    ["csgo_m9_damascus"] = 10,
    ["csgo_m9_ddpat"] = 10,
    ["csgo_m9_doppler_phase1"] = 10,
    ["csgo_m9_doppler_phase2"] = 10,
    ["csgo_m9_doppler_phase3"] = 10,
    ["csgo_m9_doppler_phase4"] = 10,
    ["csgo_m9_doppler_ruby"] = 6,
    ["csgo_m9_doppler_sapphire"] = 6,
    ["csgo_m9_fade"] = 10,
    ["csgo_m9_freehand"] = 10,
    ["csgo_m9_gamma_doppler"] = 10,
    ["csgo_m9_lore"] = 10,
    ["csgo_m9_marblefade"] = 10,
    ["csgo_m9_rustcoat"] = 10,
    ["csgo_m9_slaughter"] = 10,
    ["csgo_m9_tiger"] = 10,
    ["csgo_m9_ultraviolet"] = 10,
    ["points:200"] = 520,
    ["points:1000"] = 260
}