ITEM.Name = "Caixa da Falchion"
ITEM.Price = 5000
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(255, 0, 100)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "falchion_key"

ITEM.PossibleItems = {
    ["csgo_falchion"] = 10,
    ["csgo_falchion_night"] = 10,
    ["csgo_fal_blackpearl"] = 10,
    ["csgo_falchion_bluesteel"] = 10,
    ["csgo_falchion_boreal"] = 10,
    ["csgo_falchion_case"] = 10,
    ["csgo_falchion_bright_water"] = 10,
    ["csgo_falchion_crimsonwebs"] = 10,
    ["csgo_falchion_damascus"] = 10,
    ["csgo_falchion_ddpat"] = 10,
    ["csgo_fal_doppler_phase1"] = 10,
    ["csgo_fal_doppler_phase2"] = 10,
    ["csgo_fal_doppler_phase3"] = 10,
    ["csgo_fal_doppler_phase4"] = 10,
    ["csgo_fal_doppler_ruby"] = 10,
    ["csgo_fal_doppler_sapphire"] = 10,
    ["csgo_falchion_fade"] = 10,
    ["csgo_falchion_freehand"] = 10,
    ["csgo_falchion_gamma_doppler"] = 10,
    ["csgo_falchion_marblefade"] = 10,
    ["csgo_falchion_rustcoat"] = 10,
    ["csgo_falchion_slaughter"] = 10,
    ["csgo_falchion_tiger"] = 10,
    ["csgo_falchion_ultraviolet"] = 10,
    ["points:200"] = 400,
    ["points:1000"] = 150
}