ITEM.Name = "Caixa da Flip"
ITEM.Price = 5000
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(0, 0, 255)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "flip_key"

ITEM.PossibleItems = {
    ["csgo_flip"] = 10,
    ["csgo_flip_night"] = 10,
    ["csgo_flip_autotronic"] = 10,
    ["csgo_flip_blackpearl"] = 10,
    ["csgo_flip_black_laminate"] = 10,
    ["csgo_flip_bluesteel"] = 10,
    ["csgo_flip_boreal"] = 10,
    ["csgo_flip_case"] = 10,
    ["csgo_flip_bright_water"] = 10,
    ["csgo_flip_crimsonwebs"] = 10,
    ["csgo_flip_damascus"] = 10,
    ["csgo_flip_ddpat"] = 10,
    ["csgo_flip_doppler_phase1"] = 10,
    ["csgo_flip_doppler_phase2"] = 10,
    ["csgo_flip_doppler_phase3"] = 10,
    ["csgo_flip_doppler_phase4"] = 10,
    ["csgo_flip_doppler_ruby"] = 10,
    ["csgo_flip_doppler_sapphire"] = 10,
    ["csgo_flip_fade"] = 10,
    ["csgo_flip_freehand"] = 10,
    ["csgo_flip_gamma_doppler"] = 10,
    ["csgo_flip_lore"] = 10,
    ["csgo_flip_marblefade"] = 10,
    ["csgo_flip_rustcoat"] = 10,
    ["csgo_flip_slaughter"] = 10,
    ["csgo_flip_tiger"] = 10,
    ["csgo_flip_ultraviolet"] = 10,
    ["points:200"] = 400,
    ["points:1000"] = 150
}