ITEM.Name = "Caixa da Gut"
ITEM.Price = 5000
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(0, 255, 0)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "gut_key"
ITEM.PossibleItems = {
	["csgo_gut"] = 10,
	["csgo_gut_night"] = 10,
	["csgo_gut_autotronic"] = 10,
	["csgo_gut_blackpearl"] = 10,
	["csgo_gut_black_laminate"] = 10,
	["csgo_gut_bluesteel"] = 10,
	["csgo_gut_boreal"] = 10,
	["csgo_gut_case"] = 10,
	["csgo_gut_bright_water"] = 10,
	["csgo_gut_crimsonwebs"] = 10,
	["csgo_gut_damascus"] = 10,
	["csgo_gut_ddpat"] = 10,
	["csgo_gut_doppler_phase1"] = 10,
	["csgo_gut_doppler_phase2"] = 10,
	["csgo_gut_doppler_phase3"] = 10,
	["csgo_gut_doppler_phase4"] = 10,
	["csgo_gut_doppler_ruby"] = 10,
	["csgo_gut_doppler_sapphire"] = 10,
	["csgo_gut_fade"] = 10,
	["csgo_gut_freehand"] = 10,
	["csgo_gut_galaxy"] = 10,
	["csgo_gut_gamma_doppler"] = 10,
	["csgo_gut_lore"] = 10,
	["csgo_gut_marblefade"] = 10,
	["csgo_gut_rustcoat"] = 10,
	["csgo_gut_slaughter"] = 10,
	["csgo_gut_tiger"] = 10,
	["csgo_gut_ultraviolet"] = 10,
	["points:200"] = 400,
	["points:1000"] = 150
}
