ITEM.Name = "Caixa da Karambit"
ITEM.Price = 5000
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(30, 30, 30)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "karambit_key"
ITEM.PossibleItems = {
	["csgo_karambit"] = 10,
	["csgo_karambit_night"] = 10,
	["csgo_karambit_autotronic"] = 10,
	["csgo_karambit_black_laminate"] = 10,
	["csgo_karambit_blackpearl"] = 10,
	["csgo_karambit_bluesteel"] = 10,
	["csgo_karambit_case"] = 10,
	["csgo_karambit_bright_water"] = 10,
	["csgo_karambit_crimsonwebs"] = 10,
	["csgo_karambit_damascus"] = 10,
	["csgo_karambit_ddpat"] = 10,
	["csgo_karambit_doppler_phase1"] = 10,
	["csgo_karambit_doppler_phase2"] = 10,
	["csgo_karambit_doppler_phase3"] = 10,
	["csgo_karambit_doppler_phase4"] = 10,
	["csgo_karambit_doppler_ruby"] = 10,
	["csgo_karambit_doppler_sapphire"] = 10,
	["csgo_karambit_fade"] = 10,
	["csgo_karambit_freehand"] = 10,
	["csgo_karambit_galaxy"] = 10,
	["csgo_karambit_gamma_doppler"] = 10,
	["csgo_karambit_hyper"] = 10,
	["csgo_karambit_lore"] = 10,
	["csgo_karambit_marblefade"] = 10,
	["csgo_karambit_rustcoat"] = 10,
	["csgo_karambit_slaughter"] = 10,
	["csgo_karambit_tiger"] = 10,
	["csgo_karambit_ultraviolet"] = 10,
	["points:200"] = 400,
	["points:1000"] = 150
}
