ITEM.Name = "Caixa da Bayonet"
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(200, 200, 0)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "bayonet_key"

ITEM.PossibleItems = {
    ["csgo_bayonet"] = 10,
    ["csgo_bayonet_night"] = 10,
    ["csgo_bayonet_autotronic"] = 10,
    ["csgo_bayonet_black_laminate"] = 10,
    ["csgo_bayonet_blackpearl"] = 6,
    ["csgo_bayonet_bluesteel"] = 10,
    ["csgo_bayonet_boreal"] = 10,
    ["csgo_bayonet_case"] = 10,
    ["csgo_bayonet_bright_water"] = 10,
    ["csgo_bayonet_crimsonwebs"] = 10,
    ["csgo_bayonet_damascus"] = 10,
    ["csgo_bayonet_ddpat"] = 10,
    ["csgo_bayonet_doppler_phase1"] = 10,
    ["csgo_bayonet_doppler_phase2"] = 10,
    ["csgo_bayonet_doppler_phase3"] = 10,
    ["csgo_bayonet_doppler_phase4"] = 10,
    ["csgo_bayonet_doppler_ruby"] = 6,
    ["csgo_bayonet_doppler_sapphire"] = 6,
    ["csgo_bayonet_fade"] = 10,
    ["csgo_bayonet_freehand"] = 10,
    ["csgo_bayonet_gamma_doppler"] = 10,
    ["csgo_bayonet_lore"] = 10,
    ["csgo_bayonet_marblefade"] = 10,
    ["csgo_bayonet_rustcoat"] = 10,
    ["csgo_bayonet_slaughter"] = 10,
    ["csgo_bayonet_tiger"] = 10,
    ["csgo_bayonet_ultraviolet"] = 10,
    ["points:200"] = 520,
    ["points:1000"] = 260
}