ITEM.Name = "Caixa da Bowie"
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(0, 200, 200)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "bowie_key"

ITEM.PossibleItems = {
    ["csgo_bowie"] = 10,
    ["csgo_bowie_night"] = 10,
    ["csgo_bowie_blackpearl"] = 6,
    ["csgo_bowie_bluesteel"] = 10,
    ["csgo_bowie_boreal"] = 10,
    ["csgo_bowie_case"] = 10,
    ["csgo_bowie_bright_water"] = 10,
    ["csgo_bowie_crimsonwebs"] = 10,
    ["csgo_bowie_damascus"] = 10,
    ["csgo_bowie_ddpat"] = 10,
    ["csgo_bowie_doppler_phase1"] = 10,
    ["csgo_bowie_doppler_phase2"] = 10,
    ["csgo_bowie_doppler_phase3"] = 10,
    ["csgo_bowie_doppler_phase4"] = 10,
    ["csgo_bowie_doppler_ruby"] = 6,
    ["csgo_bowie_doppler_sapphire"] = 6,
    ["csgo_bowie_fade"] = 10,
    ["csgo_bowie_freehand"] = 10,
    ["csgo_bowie_gamma_doppler"] = 10,
    ["csgo_bowie_marblefade"] = 10,
    ["csgo_bowie_rustcoat"] = 10,
    ["csgo_bowie_slaughter"] = 10,
    ["csgo_bowie_tiger"] = 10,
    ["csgo_bowie_ultraviolet"] = 10,
    ["points:200"] = 460,
    ["points:1000"] = 230
}