ITEM.Name = "Caixa da Huntsman"
ITEM.Material = PS.Materials["case"]
ITEM.Color = Color(255, 0, 0)
ITEM.EquipLabel = "Abrir Caixa"
ITEM.SupressEquip = true
ITEM.Lootable = true
ITEM.Key = "huntsman_key"

ITEM.PossibleItems = {
    ["csgo_huntsman"] = 10,
    ["csgo_huntsman_night"] = 10,
    ["csgo_huntsman_am_marble_fade"] = 10,
    ["csgo_huntsman_blackpearl"] = 6,
    ["csgo_huntsman_bluesteel"] = 10,
    ["csgo_huntsman_boreal"] = 10,
    ["csgo_huntsman_case"] = 10,
    ["csgo_huntsman_bright_water"] = 10,
    ["csgo_huntsman_crimsonwebs"] = 10,
    ["csgo_huntsman_damascus"] = 10,
    ["csgo_huntsman_ddpat"] = 10,
    ["csgo_huntsman_phase1"] = 10,
    ["csgo_huntsman_phase2"] = 10,
    ["csgo_huntsman_phase3"] = 10,
    ["csgo_huntsman_phase4"] = 10,
    ["csgo_huntsman_doppler_ruby"] = 6,
    ["csgo_huntsman_doppler_sapphire"] = 6,
    ["csgo_huntsman_fade"] = 10,
    ["csgo_huntsman_freehand"] = 10,
    ["csgo_huntsman_gamma_doppler"] = 10,
    ["csgo_huntsman_marblefade"] = 10,
    ["csgo_huntsman_rustcoat"] = 10,
    ["csgo_huntsman_slaughter"] = 10,
    ["csgo_huntsman_tiger"] = 10,
    ["csgo_huntsman_ultraviolet"] = 10,
    ["points:200"] = 480,
    ["points:1000"] = 240
}